spring:
  profiles:
    active: local
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3316/test?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              org.hibernate.type.descriptor.sql.BasicBinder: TRACE